name: Run Daily Playwright Script

on:
  schedule:
    - cron: '30 23 * * *'  # 5:00 AM IST daily
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run script
        run: |
          cd ar-travels-csv-download
          python arcsvscript.py

